query getAllBlogs {
  blogsConnection {
    totalCount
    edges {
      node {
        _sys {
          filename
          path
        }
        ...BlogsParts
      }
    }
  }
}

query getAllDocs {
  docsConnection {
    totalCount
    edges {
      node {
        _sys {
          filename
          path
        }
        ...DocsParts
      }
    }
  }
}
